version: '3.8'

services:
  kerio-vpn:
    image: kerio-vpn:1.0
    container_name: ${KERIO_VPN_NAME}
    restart: unless-stopped
    privileged: true
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    networks:
      - ${KERIO_VPN_NETWORK}
    volumes:
      - ./erioWorkPlace/vpn-kerio/kerio-kvc.conf:/etc/kerio-kvc.conf
      - ./kerio.sh:/opt/kerio.sh
    entrypoint: >
      sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward &&
             iptables -t nat -A POSTROUTING -o kvnet -j MASQUERADE &&
             /entrypoint.sh"

  forti-test:
    container_name: ${FORTI_VPN_NAME}
    image: forti-clinet:latest
    user: "root:root"
    privileged: true
    networks:
      - ${FORTI_VPN_NETWORK}
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    volumes:
      - ./fortiWorkPlace/forti-vpn:/etc/openfortivpn/config
      - ./fortiWorkPlace/forti.sh:/opt/forti.sh
    command: /opt/forti.sh

networks:
  ${KERIO_VPN_NETWORK}:
    driver: bridge
  ${FORTI_VPN_NETWORK}:
    driver: bridge
