version: '3'
services:
  forti:
    network_mode: "host"
    container_name: <container-name>
    image: <image-name>
    user: "root:root"
    privileged: true
    volumes:
      - ./config:/etc/openfortivpn/config
      - ./forti.sh:/opt/forti.sh
    command: /opt/forti1.sh
